### ISSUE TITLE
panic in create autogenerate file

### ISSUE THREAD

**Issue by DmitriyPrischep** [sirkon/ldetool#36]
```
ProcStats = 
    Pid(int32) ' '
    Comm(string) ' '
    State($uint8) ' '[1]
    Ppid(int32) ' '
    Pgrp(int32) ' '
    Session(int32) ' '
    TtyNr(int32) ' '
    Tpgid(int32) ' '
    Flags(uint32) ' '
    Minflt(uint32) ' '
    Cminflt(uint32) ' '
    Majflt(uint32) ' '
    Cmajflt(uint32) ' '
    Utime(uint32) ' '
    Stime(uint32) ' '
    Cutime(int32) ' '
    Cstime(int32) ' '
    Priority(int32) ' '
    Nice(int64) ' '
    NumThreads(int64) ' '
    Itrealvalue(int64) ' '
    Starttime(uint64) ' '
    Vsize(uint32) ' '
    Rss(int32) ' '
    Rsslim(uint32) ' '
    Startcode(uint32) ' '
    Endcode(uint32) ' '
    StartStack(uint32) ' '
    Kstkesp(uint32) ' '
    Kstkeip(uint32) ' '
    Signal(uint32) ' '
    Blocked(uint32) ' '
    Sigignore(uint32) ' '
    Sigcatch(uint32) ' '
    Wchan(uint32) ' '
    Nswap(uint32) ' '
    Cnswap(uint32) ' '
    ExitSignal(int32) ' '
    Processor(int32) ' '
    RtPriority(uint32) ' '
    Policy(uint32) ' '
    DelayacctBlkioTicks(uint64) ' '
    GuestTime(uint32) ' '
    CguestTime(uint32) ' '
    StartData(uint32) ' '
    EndData(uint32) ' '
    StartBrk(uint32) ' '
    ArgStart(uint32) ' '
    ArgEnd(uint32) ' '
    EnvStart(uint32) ' '
    EnvEnd(uint32) ' '
    ExitCode(int32)

;
```

```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 1 [running]:
main.generate.func1(0xc0001b1f28, 0xc0001b1eb0, 0xc0001343c0, 0xc0001b1ea8)
	go/src/github.com/sirkon/ldetool/ldetool.go:156 +0x701
panic(0x6ea840, 0x7a9e30)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/sirkon/ldetool/internal/generator/gogen.(*Generator).AddField(0xc0000daa00, 0xc00017f3d8, 0x5, 0xc00017f3f0, 0x6, 0x7b9840, 0xc00020c210, 0x0, 0x0)
	go/src/github.com/sirkon/ldetool/internal/generator/gogen/generator.go:238 +0xa48
github.com/sirkon/ldetool/internal/srcbuilder.(*SrcBuilder).DispatchTake.func2(0x0, 0x0)
	go/src/github.com/sirkon/ldetool/internal/srcbuilder/dispatching.go:389 +0x88
github.com/sirkon/ldetool/internal/srcbuilder.(*SrcBuilder).BuildRule(0xc0000e6e10, 0xc000269500, 0x75363c, 0x1e)
	go/src/github.com/sirkon/ldetool/internal/srcbuilder/builder.go:72 +0xbb
main.generate(0xc0001343c0, 0x0, 0x0)
	go/src/github.com/sirkon/ldetool/ldetool.go:220 +0x9ca
main.main()
```

**Comment by sirkon** [comment]
Fixed. Check it out please.
